flags: {}

extra-package-dbs: []

allow-newer: true
resolver: lts-9.1

nix:
    packages: [gmp,git]

extra-deps:
  - universum-0.8.0
  #   allow-newer: true

packages:
  - location: .

  - location:
      git: https://github.com/dhall-lang/dhall-json
      commit: d6adaa265dcf8ab5899396b05d612b2d8092dca4
    extra-dep: true
  - location:
      git: https://github.com/dhall-lang/dhall-haskell
      commit: 4a085aa3d622886cf7dd96a1ad475ba914d5ab1f
    extra-dep: true
